cbnb_admin:
    resource: "@CBNBAdminBundle/Controller/"
    type:     annotation
    prefix:   /admin

app:
    resource: "@CBNBFEBundle/Controller/"
    type:     annotation
    prefix:   /
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"