# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
  base.roles_service:
    class: CBNBBaseBundle\Services\RolesService
    calls:
     - [ setContainer, [ "@service_container" ] ]